/**
 * Documentação com Swagger - CodesDevs
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUserDto { 
    /**
     * Endereço de email válido do usuário.
     */
    email: string;
    /**
     * Nome de usuário único.
     */
    username: string;
    /**
     * CPF ou CNPJ do usuário. Este campo é opcional.
     */
    cpfCnpj?: string;
    /**
     * Senha do usuário. Deve ter entre 3 e 20 caracteres.
     */
    password: string;
    /**
     * ID opcional do parceiro associado ao usuário.
     */
    partnerId?: string;
    /**
     * ID do canil associado ao usuário, se aplicável.
     */
    kennelId?: number;
    /**
     * Indica se o usuário está ativo
     */
    isActive: boolean;
}

