/**
 * Documentação com Swagger - CodesDevs
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreatePersonDto { 
    /**
     * Nome completo da pessoa
     */
    name: string;
    /**
     * Nome fantasia, caso aplicável
     */
    fantasyName?: string;
    /**
     * CPF ou CNPJ da pessoa
     */
    cpfCnpj?: string;
    /**
     * Endereço de email válido
     */
    email: string;
    /**
     * Número de telefone principal
     */
    phone1?: string;
    /**
     * Número de telefone secundário
     */
    phone2?: string;
    /**
     * Data de nascimento da pessoa
     */
    birthDate?: string;
    /**
     * Anotações ou observações sobre a pessoa
     */
    notes?: string;
}

