/**
 * Documentação com Swagger - CodesDevs
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InitializeSessionDto { 
    /**
     * numero da sessão a ser inicializada
     */
    number: string;
    /**
     * Descrição da sessão a ser inicializada
     */
    name: string;
}

