/**
 * Documentação com Swagger - CodesDevs
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SendMessageDto { 
    /**
     * ID da sessão do WhatsApp
     */
    number: string;
    /**
     * Número de telefone para enviar a mensagem
     */
    phoneNumber: string;
    /**
     * Conteúdo da mensagem a ser enviada
     */
    message: string;
}

