/**
 * Documentação com Swagger - CodesDevs
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateConfigDto { 
    /**
     * Nome da configuração
     */
    name: string;
    /**
     * Endereço de e-mail
     */
    email: string;
    /**
     * Número de celular
     */
    mobile: string;
    /**
     * Telefone residencial ou comercial
     */
    phone1?: string;
    /**
     * Telefone alternativo
     */
    phone2?: string;
    /**
     * Endereço do local
     */
    place: string;
    /**
     * Número do local
     */
    number: string;
    /**
     * Complemento do endereço
     */
    complement?: string;
    /**
     * Bairro
     */
    neighborhood: string;
    /**
     * Cidade
     */
    city: string;
    /**
     * Estado (UF)
     */
    state: string;
    /**
     * Código postal
     */
    zipCode: string;
}

